# AUthor: jian zhang
# *---utf-8---*
# Date: 2025-10-4
# Analsis Software
# ------- software path -------- #
software:
  signalp: /home/jzhang/software/miniconda3/bin/signalp6
  tmhmm : /home/jzhang/software/DTU_software/tmhmm-2.0c/bin/tmhmm
  interproscan:  /data/jzhang/reference/InterProScan/interproscan-5.75-106.0/interproscan.sh
  diamond: /home/jzhang/software/diamond-2.1.15/bin/diamond
# ------- software parameter -------- #
# Raw data QC & Trimming
trim:
  length_required: 75
  quality_threshold: 25
  adapter_fasta: "./data/Illumina_Universal_Adapter.fa"
long_read_qc:
  length_required: 300
  qualified_quality_phred: 15
rnabloom:
  min_length: 150
fastq_screen:
  run: true
  path: /home/jzhang/software/FastQ-Screen-0.16.0/fastq_screen
  conf: /home/jzhang/software/FastQ-Screen-0.16.0/fastq_screen.conf
  subset: 100000
  aligner: Bowtie2
# Resource parameter for a specific part of the analysis
threads:
  short_md5_check: 20
  long_md5_check: 10
  fastp: 6
  nanoplot: 10
  fastplong: 10
  fastq_screen: 10
  star_mapping : 16
  samtools_sort: 8
  rnabloom: 30
  bowtie2_build: 20
  bowtie_mapping: 20
  samtools_threads: 4
  busco: 16
  bowtie_mapping: 10
  samtools_mapping: 5
  corset_cluster: 1
  salmon_index: 20
  salmon_quant: 10
  busco_salmon: 20
  transrate: 35
  TD2.LongOrfs: 20
  mmseqs: 20
  hmmscan: 30
  interproscan: 20
  diamond_blastp_threads: 30
  preprocess_interpro: 20
  signalp: 8
# ------- pipeline parameter -------- #
log_level: "INFO"
busco:
  lineage: "/data/jzhang/reference/busco/lineages/embryophyta_odb10"
  mode: "transcriptome"
cdhit:
  coverage: 0.95
salmon:
  librarytype: "A"
abundance_estimates:
  est_method: salmon
mmseqs:
  swissprot_database: /data/jzhang/reference/mmseqs/UniProtKB/swissprot
annotate:
  uniport_database: /data/jzhang/reference/uniport/swissprot_annotations.tsv
  Pfam_A: /data/jzhang/reference/Pfam/Pfam-A.hmm
deg:
  pval: 0.05
  lfc: 1
signalp:
  mode: slow-sequential
r1_suffix: .R1.fq.gz
r2_suffix: .R2.fq.gz
print_target: true
# -------- END -------- #